apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: welcome-prod
  namespace: welcome-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "9"
spec:
  project: default
  source:
    path: app/overlays/prod/
    repoURL: http://gitea-http.scm.svc.cluster.local:3000/developer/welcome-app
    targetRevision: main
  destination:
    namespace: welcome-prod
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
